### ISSUE TITLE
Adding targets

### ISSUE THREAD

**Issue by dadoeyad** [j-white/python-vuforia#1]
Have you been able to add targets via the API with Python?
I'm trying to add a function to your class and failed so far.

**Comment by interactivetech** [comment]
Hey all, I am trying to upload a target and I get this error:

  print v.add_target({"name": "zxczxc", "width": "1.0", "image": image})
  File "vuforia.py", line 157, in add_target
    response = self._get_authenticated_response(req)
  File "vuforia.py", line 123, in _get_authenticated_response
    raise VuforiaFail(e, response)
__main__.VuforiaFail

Not really sure how to debug, so any help would be amazing!

Also, there is no metadata file in the folder, so what should I add in the metadata when creating a new metadata file?

**Comment by emilgeorgejames1** [comment]
Haii,i fixed this issues and tested.
Added a float for assigning width.
example:
`print v.add_target({"name": "name", "width":float(320), "image": image, "application_metadata": metadata, "active_flag": 1})`
